fragment ImageFragment on FileField {
  alt
  basename
  format
  height
  id
  mimeType
  size
  title
  url
  width
  customData
  responsiveImage {
    alt
    aspectRatio
    base64
    bgColor
    height
    sizes
    src
    srcSet
    webpSrcSet
    title
    width
  }
  video {
    thumbnailUrl
    streamingUrl
    mp4high: mp4Url(res: high)
    mp4med: mp4Url(res: medium)
    mp4low: mp4Url(res: low)
    framerate
    duration 
  }
}