#import "./fragments/SiteFragment.graphql"
#import "./fragments/PageFragment.graphql"

query Global {
	site: _site {
		...SiteFragment
	}
	menu: allMenus(filter: { parent: { exists: "*" } }) {
		id
		label
		page {
			...PageFragment
		}
		children {
			id
			label
			page {
				...PageFragment
			}
		}
	}
}