#import "./fragments/SiteFragment.graphql"
#import "./fragments/PageFragment.graphql"
#import "./fragments/ImageFragment.graphql"

query Global {
	site: _site {
		...SiteFragment
	}
	menu: allMenus(filter: { parent: { exists: "*" } }) {
		id
		label
		page {
			...PageFragment
		}
		children {
			id
			label
			page {
				...PageFragment
			}
		}
	}
	menuFooter: allMenuFooters{
		id
		label
		page{
			... on InvestmentPhilosophyRecord {
				title
				slug
			}
			... on ResponsibilityRecord {
				title
				slug
			}
			... on SkabholmenGroupRecord {
				title
				slug
			}
			... on TeamRecord {
				title
				slug
			}
		}
	}
	contact {
		email
		phone
		address(markdown: false)
		social{
			id
			name
			url
			icon{
				...ImageFragment
			}
		}
	}
}