#import './fragments/ProjectFragment.gql'

query AllProjects {
	projects: allProjects {
		...ProjectFragment
	}
}

query Project($slug: String!) {
	project(filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}
